### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by PratikGarai** [PratikGarai/Airline-Reservation-System#1]
- [ ] Make time based auto discarding feature of flights

- [ ] Preliminary validation of form using js + form styling

- [ ] Make a transaction simulation
